@startuml DB context

rectangle "User" {
    [message]
}

package "Streamlit" #LightPink {
    prompt-[WEB]
}
rectangle "Ollama"{
    [API]
}

database "DB" {
    [context]
    [userId]
}

message --> WEB : send message with userId
WEB --> DB : get context by userId 
DB --> API 
WEB --> API : send message
API --> DB 



@enduml